export const MICRONUTRIENT_DRI = {
  vit_d_mcg: { male: 15, female: 15 },
  vit_b12_mcg: { male: 2.4, female: 2.4 },
  vit_c_mg: { male: 90, female: 75 },
  vit_a_mcg: { male: 900, female: 700 },
  folate_mcg: { male: 400, female: 400 },
  iron_mg: { male: 8, female: 18 },
  calcium_mg: { male: 1000, female: 1000 },
  magnesium_mg: { male: 420, female: 320 },
  zinc_mg: { male: 11, female: 8 },
  potassium_mg: { male: 3400, female: 2600 },
  sodium_mg: { male: 2300, female: 2300 },
  omega3_g: { male: 1.6, female: 1.1 },
} as const;

export const NUTRIENT_LABELS: Record<string, string> = {
  vit_d_mcg: 'Vitamina D',
  vit_b12_mcg: 'Vitamina B12',
  vit_c_mg: 'Vitamina C',
  vit_a_mcg: 'Vitamina A',
  folate_mcg: 'Folato',
  iron_mg: 'Hierro',
  calcium_mg: 'Calcio',
  magnesium_mg: 'Magnesio',
  zinc_mg: 'Zinc',
  potassium_mg: 'Potasio',
  omega3_g: 'Omega-3',
  protein_g: 'Proteína',
  carbs_g: 'Hidratos',
  fat_g: 'Grasas',
  fiber_g: 'Fibra',
  water_ml: 'Agua',
};

export const NUTRIENT_UNITS: Record<string, string> = {
  vit_d_mcg: 'mcg',
  vit_b12_mcg: 'mcg',
  vit_c_mg: 'mg',
  vit_a_mcg: 'mcg',
  folate_mcg: 'mcg',
  iron_mg: 'mg',
  calcium_mg: 'mg',
  magnesium_mg: 'mg',
  zinc_mg: 'mg',
  potassium_mg: 'mg',
  omega3_g: 'g',
  protein_g: 'g',
  carbs_g: 'g',
  fat_g: 'g',
  fiber_g: 'g',
  water_ml: 'ml',
};
